name: status_bar_control_plus
description: Status Bar Control Plus, lets you control the status bar color, style (theme), visibility, and translucent properties across iOS and Android.
version: 3.3.0
homepage: https://github.com/Gulshank61/statusbar_control_plus

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.foo.statusbarcontrolplus
        pluginClass: StatusBarControlPlusPlugin
      ios:
        pluginClass: StatusBarControlPlusPlugin
