name: Flutter_Tests

on:
  push:
    branches:
      - dev/*
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🛬 Checkout the code
        uses: actions/checkout@v2.4.0
      - name: 🚚 Setup Flutter and version
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "2.10.2"
      - name: 📦 Install packages
        run: flutter pub get
      - name: 🧾 Run tests
        run: cd example && flutter test
